### ISSUE TITLE
what's version of your numpy

### ISSUE THREAD

**Issue by yang2022** [zeruniverse/neural-colorization#5]
i meet the error    AttributeError: 'numpy.ufunc' object has no attribute '__module__'
what's version of your numpy or caused by other reasons,thanks

**Comment by zeruniverse** [comment]
Try Python 3.6 instead of 3.7

**Comment by yang2022** [comment]
then i meet  RuntimeError: size mismatch, m1: [20 x 512], m2: [2048 x 1] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249,i tried to change,but didn't work

**Comment by yang2022** [comment]
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f0c2ca9af90>> ignored

**Comment by zeruniverse** [comment]
please post the full exception stack. which file did you run?

**Comment by yang2022** [comment]
python train.py -d train -c checkpoints
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    g_loss_gan = adversarial_loss(D(gen_imgs), valid)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 162, in forward
    x = self.fc(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: size mismatch, m1: [20 x 512], m2: [2048 x 1] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
i upgrade pytorch,then it come to this,thanks

**Comment by zeruniverse** [comment]
Please check README. Only support python 3.6

**Comment by yang2022** [comment]
python3.6
Python 3.6.4 (default, Apr  3 2019, 16:48:01) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> train.py -d train -c checkpoints
  File "<stdin>", line 1
    train.py -d train -c checkpoints
                    ^
SyntaxError: invalid syntax
>>> train.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'train' is not defined
>>> train.py -d train
  File "<stdin>", line 1
    train.py -d train
                    ^
SyntaxError: invalid syntax
>>> train.py -d ./train -c ./checkpoints
  File "<stdin>", line 1
    train.py -d ./train -c ./checkpoints
                 ^
SyntaxError: invalid syntax
>>>

**Comment by zeruniverse** [comment]
Could you run it as

‘python3 train.py -d ...’?

It’s really weird that argparser doesn’t work... maybe try ‘python3 train.py —help’ first

**Comment by zeruniverse** [comment]
resolved?

**Comment by yang2022** [comment]
no,i try to reinstall pytorch

**Comment by yang2022** [comment]
It still didn't work
python3.6
Python 3.6.4 (default, Apr  3 2019, 16:48:01) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> train.py -d train -c checkpoints
  File "<stdin>", line 1
    train.py -d train -c checkpoints
                    ^
SyntaxError: invalid syntax
>>> exit()
 python3.6 train.py -d train -c checkpoints
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    g_loss_gan = adversarial_loss(D(gen_imgs), valid)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torchvision/models/resnet.py", line 162, in forward
    x = self.fc(x)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: size mismatch, m1: [20 x 512], m2: [2048 x 1] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266

**Comment by zeruniverse** [comment]
As stated in README, training is only supported for images at size 256*256.
If your images are not that size, you should use the tool script provided
in this repo.

**Comment by yang2022** [comment]
我的图像数据确实是256*256，我也以为数据没有导进去，但是后面我输出了一下路径，发现是可以显示的

**Comment by zeruniverse** [comment]
但是我能跑 你还是那个错误？

**Comment by zeruniverse** [comment]
solved?

**Comment by zeruniverse** [comment]
@yang2022 moved to #6 please follow my last comment there
